### ISSUE TITLE
RNAfold: invalid option -- n

### ISSUE THREAD

**Issue by Cristinex** [nf-core/smrnaseq#155] opened 2022-05-23 08:55 UTC
## Check Documentation

I have checked the following places for your error:

- [Y ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [doesn't exist] [nf-core/smrnaseq pipeline documentation](https://nf-co.re/nf-core/smrnaseq/usage)

## Description of the bug

The pipeline crash with error: File mirdeep_runs/run_23_05_2022_t_08_12_30_CL100189714_L01_31_trimmed_collapsed/output.mrd is empty. It seemed that miRdeep2 repoorted bad results. However, as I checked the fastqc report, the quality of samples are all fine. I checked this output.mrd of other samples, they are not empty, however. 
## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: nextflow run nf-core/smrnaseq -r 1.1.0 --input '*.fastq.gz' -profile docker --genome GRCh38 --mature /share/home/grp-huangxd/apps/iGenomes/Homo_sapiens/UCSC/hg38/Annotation/SmallRNA/mature.fa --hairpin /share/home/grp-huangxd/apps/iGenomes/Homo_sapiens/UCSC/hg38/Annotation/SmallRNA/hairpin.fa --bt_index /share/home/grp-huangxd/apps/iGenomes/Homo_sapiens/UCSC/hg38/Sequence/BowtieIndex/ --three_prime_adapter AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
2. See error:  File mirdeep_runs/run_23_05_2022_t_08_12_30_CL100189714_L01_31_trimmed_collapsed/output.mrd is empty
3. In trimmed_collapsed.log, it showed RNAfold: invalid option -- n

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: HPC
- Executor: docker
- OS: CentOS
- Version 7

Another question is that is there anyway to resume after fixing the problem?

Thank you!

**Comment by apeltzer** [comment] 2023-02-17 22:06
Closing as I cannot reproduce (anymore) - please reopen after testing with `dev` (pre-2.2.0 release)

**Closed by apeltzer** 2023-02-17 22:06 UTC
Labels: bug
