### ISSUE TITLE
edgeR_mirna error

### ISSUE THREAD

**Issue by mshulewitz** [nf-core/smrnaseq#31] opened 2019-12-19 21:10 UTC
Running smrnaseq on an AWS EC2 (Ubuntu 18.04, 64 GB memory, 16 cpu) with the following command line:

```bash
nextflow run nf-core/smrnaseq -r 1.0.0 -profile docker \
--reads 'sample1.*' \
--genome 'GRCh37' \
--max_memory '60.GB' \
 --outdir smrnaseq_output \
--protocol cats
```

gives the following error:

```
Error executing process > 'edgeR_mirna'

Caused by:
  Process `edgeR_mirna` terminated with an error exit status (1)

Command executed:

  edgeR_miRBase.r Kit4RNA3.mature.stats Kit4RNA3.hairpin.stats

Command exit status:
  1

Command output:
  $mature
  [1] "sample1.mature.stats"

  $hairpin
  [1] "sample1.hairpin.stats"

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Loading required package: limma
  Loading required package: edgeR
  Loading required package: statmod
  Loading required package: data.table
  Loading required package: gplots

  Attaching package: ‘gplots’

  The following object is masked from ‘package:stats’:

      lowess

  Error in apply(data, 1, function(row) all(row == 0)) :
    dim(X) must have a positive length
  Execution halted
```

Running `edgeR_miRBase.r` locally also gives same error.

**Comment by lpantano** [comment] 2019-12-20 18:21
Hi,

I think something is wrong with the input. Can you go into the working folder and check the input files, if they are not empty?

maybe try to run the R script in an interactive version helps more as well.

**Comment by mshulewitz** [comment] 2019-12-20 19:32
I pulled the test fastq and reference files using the paths in test.config and rerun with the following command line and was successful:

nextflow run nf-core/smrnaseq -r 1.0.0 -profile docker \
--reads 'fastq_repo/sample_*' \
--max_memory '60.GB' \
--mature 'smrnaseq_ref/mature.fa' \
--hairpin 'smrnaseq_ref/hairpin.fa' \
--bit_index 'reference/genome' \
--fasta 'smrnaseq_ref/genes.gtf' \
--gtf 'smrnaseq_ref/hsa.gff3' \
--mirtrace_species 'hsa' \
--outdir smrnaseq_output

However, if I only process a single fastq (eg: --reads 'fastq_repo/sample_1.fastq.gz') I receive the error message. In this case, the input files sample_1.hairpin.stats and sample_1.mature.stats are in the working directory for edgeR_mirna process.

**Comment by lpantano** [comment] 2020-01-09 12:19
Ah, ok, I see the error, it is only one sample the problem…I would need to
take a look into the R code exactly to know why. (Sorry for the delay I
have been away until now.)



From: mshulewitz <notifications@github.com> <notifications@github.com>
Reply: nf-core/smrnaseq
<reply@reply.github.com>
<reply@reply.github.com>
Date: December 20, 2019 at 2:32:58 PM
To: nf-core/smrnaseq <smrnaseq@noreply.github.com>
<smrnaseq@noreply.github.com>
Cc: Lorena Pantano <lorena.pantano@gmail.com> <lorena.pantano@gmail.com>,
Comment <comment@noreply.github.com> <comment@noreply.github.com>
Subject:  Re: [nf-core/smrnaseq] edgeR_mirna error (#31)

I pulled the test fastq and reference files using the paths in test.config
and rerun with the following command line and was successful:

nextflow run nf-core/smrnaseq -r 1.0.0 -profile docker
--reads 'fastq_repo/sample_*'
--max_memory '60.GB'
--mature 'smrnaseq_ref/mature.fa'
--hairpin 'smrnaseq_ref/hairpin.fa'
--bit_index 'reference/genome'
--fasta 'smrnaseq_ref/genes.gtf'
--gtf 'smrnaseq_ref/hsa.gff3'
--mirtrace_species 'hsa'
--outdir smrnaseq_output

However, if I only process a single fastq (eg: --reads
'fastq_repo/sample_1.fastq.gz') I receive the error message. In this case,
the input files sample_1.hairpin.stats and sample_1.mature.stats are in the
working directory for edgeR_mirna process.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nf-core/smrnaseq/issues/31?email_source=notifications&email_token=AAML6HH6A5ZNKKSWGGSGO7LQZUMWVA5CNFSM4J5QFHPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHN6MVQ#issuecomment-568059478>,
or unsubscribe

**Comment by apeltzer** [comment] 2022-10-11 08:04
Goign to close this as the issue is very likely not there anymore in the current dev and soon release - please retest again 👍🏻

**Closed by apeltzer** 2022-10-11 08:04 UTC
Labels: bug
