### ISSUE TITLE
Error in the collapse process

### ISSUE THREAD

**Issue by fedeago** [nf-core/smrnaseq#35] opened 2020-02-07 08:21 UTC
Hi, thanks for your work. I'm tring to run this pipeline but it stop with the following error.
```
Error executing process > 'bowtie_miRBase_hairpin_collapsed (10.umitransformed.clean.fastq 10.umitransformed.clean_trimmed_umi_trimmed.fastq)

Caused by:
  No such property: baseName for class: nextflow.util.BlankSeparatedList

Source block:
  index_base = index.toString().tokenize(' ')[0].tokenize('.')[0]
  prefix = reads.baseName
  seq_center = params.seq_center ? "--sam-RG ID:${prefix} --sam-RG 'CN:${params.seq_center}'" : ''
  """
      bowtie \\
          $index_base \\
          -p ${task.cpus} \\
          -t \\
          -k 50 \\
          -a \\
          --best \\
          --strata \\
          -e 99999 \\
          --chunkmbs 2048 \\
          -q <(cat $reads) \\
          -S $seq_center \\
          | samtools view -bS - > ${prefix}.bam
      """

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```
i use that pipeline with this configuration:

`~/nextflow run nf-core/smrnaseq --reads '../cleaned/*.umitransformed.clean.fq.gz' --min_length 17 --genome 'GRCh37' --skipQC -profile singularity`

How could i resolve this problem?

**Comment by ewels** [comment] 2020-02-07 10:09
Hi @fedeago,

What version of Nextflow are you using? Could you please post the `.nextflow.log` file from the run?

Phil

**Comment by fedeago** [comment] 2020-02-07 10:34
I have't the .nexflow.log file. I use it with slurm, and the reads that i use are already trimmed. I can post the slurm.out file with the standard output of the pipeline. The version of nextflow is 19.10.0.

**Comment by ewels** [comment] 2020-02-07 10:57
It looks like the problem is the `prefix = reads.baseName` bit. I guess it works when there is only one file in the `collapsed_fasta` channel, but it's breaking here because there is more than one fastq being generated by the `seqcluster collapse` process for some reason.

@lpantano could you have a look at this please? Am I right?

Phil

**Comment by fedeago** [comment] 2020-02-07 11:00
[slurm.txt](https://github.com/nf-core/smrnaseq/files/4170380/slurm.txt)

**Comment by lpantano** [comment] 2020-02-08 23:16
@ewels you are right, it is detecting UMIs and creating two files, I will work on the fix on Monday.

**Comment by apeltzer** [comment] 2022-01-03 13:03
Looks like this is long resolved by @lpantano 👍🏻

**Closed by apeltzer** 2022-01-03 13:03 UTC
Labels: bug
