### ISSUE TITLE
Split FastQ Support

### ISSUE THREAD

**Issue by alexmascension** [nf-core/smrnaseq#265] opened 2023-08-10 14:25 UTC
### Description of the bug

I'm running the pipeline with several files per sample. This is a part of the `samplesheet.csv` for reference:

```
sample,fastq_1
109-1,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-1_S1_L001_R1_001.fastq.gz
109-1,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-1_S1_L002_R1_001.fastq.gz
109-1,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-1_S1_L003_R1_001.fastq.gz
109-1,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-1_S1_L004_R1_001.fastq.gz
109-3,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-3_S2_L001_R1_001.fastq.gz
109-3,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-3_S2_L002_R1_001.fastq.gz
109-3,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-3_S2_L003_R1_001.fastq.gz
109-3,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-3_S2_L004_R1_001.fastq.gz
109-5,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-5_S3_L001_R1_001.fastq.gz
109-5,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-5_S3_L002_R1_001.fastq.gz
109-5,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-5_S3_L003_R1_001.fastq.gz
109-5,data/Gorostidi_BioDonosti_230711-24796800/FASTQ/109Gorostidi-5_S3_L004_R1_001.fastq.gz
```

Each sample has 4 files.  When running nf-core, after running fastqc and fastc, in the process `NFCORE_SMRNASEQ:SMRNASEQ:MIRTRACE:MIRTRACE_RUN (1)` the process fails.

The complete state at the moment of failure is the following:

```
[1f/d72950] process > NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)                     [100%] 1 of 1 ✔
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:CAT_FASTQ                                                           -
executor >  local (299)
[1f/d72950] process > NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)                     [100%] 1 of 1 ✔
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:CAT_FASTQ                                                           -
executor >  local (299)
[1f/d72950] process > NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)                     [100%] 1 of 1 ✔
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:CAT_FASTQ                                                           -
executor >  local (299)
[1f/d72950] process > NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)                     [100%] 1 of 1 ✔
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:CAT_FASTQ                                                           -
executor >  local (299)
[1f/d72950] process > NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)                     [100%] 1 of 1 ✔
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:CAT_FASTQ                                                           -
[3c/fefab6] process > NFCORE_SMRNASEQ:SMRNASEQ:FASTQC_FASTP:FASTQC_RAW (117-3)                                     [100%] 112 of 112 ✔
[39/314d35] process > NFCORE_SMRNASEQ:SMRNASEQ:FASTQC_FASTP:FASTP (117-5)                                          [100%] 112 of 112 ✔
[dd/655dac] process > NFCORE_SMRNASEQ:SMRNASEQ:FASTQC_FASTP:FASTQC_TRIM (112-2)                                    [  3%] 4 of 112
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRTRACE:MIRTRACE_RUN                                               -
[9b/184d5e] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:PARSE_MATURE                                            [100%] 1 of 1 ✔
[91/4958ca] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:FORMAT_MATURE (mature.fa_igenome.fa)                    [100%] 1 of 1 ✔
[ac/4ecd2d] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:PARSE_HAIRPIN                                           [100%] 1 of 1 ✔
[2c/dbda1e] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:FORMAT_HAIRPIN (hairpin.fa_igenome.fa)                  [100%] 1 of 1 ✔
[1c/266128] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE                                            [100%] 1 of 1 ✔
[20/6c5434] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_HAIRPIN                                           [100%] 1 of 1 ✔
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BOWTIE_MAP_MATURE                                       -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BOWTIE_MAP_HAIRPIN                                      -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_MATURE:SAMTOOLS_SORT                          -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_MATURE:SAMTOOLS_INDEX                         -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_MATURE:BAM_STATS_SAMTOOLS:SAMTOOLS_STATS      -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_MATURE:BAM_STATS_SAMTOOLS:SAMTOOLS_FLAGSTAT   -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_MATURE:BAM_STATS_SAMTOOLS:SAMTOOLS_IDXSTATS   -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_HAIRPIN:SAMTOOLS_SORT                         -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_HAIRPIN:SAMTOOLS_INDEX                        -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_HAIRPIN:BAM_STATS_SAMTOOLS:SAMTOOLS_STATS     -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_HAIRPIN:BAM_STATS_SAMTOOLS:SAMTOOLS_FLAGSTAT  -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BAM_STATS_HAIRPIN:BAM_STATS_SAMTOOLS:SAMTOOLS_IDXSTATS  -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:EDGER_QC                                                -
[d3/64ebfb] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:SEQCLUSTER_SEQUENCES (111-3_seqcluster)                 [  4%] 5 of 112
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:BOWTIE_MAP_SEQCLUSTER                                   -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:MIRTOP_QUANT                                            -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:TABLE_MERGE                                             -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:INDEX_GENOME                                           [  0%] 0 of 1
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:BOWTIE_MAP_GENOME                                      -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:BAM_SORT_SAMTOOLS:SAMTOOLS_SORT                        -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:BAM_SORT_SAMTOOLS:SAMTOOLS_INDEX                       -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:BAM_SORT_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_STATS    -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:BAM_SORT_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_FLAGSTAT -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:GENOME_QUANT:BAM_SORT_SAMTOOLS:BAM_STATS_SAMTOOLS:SAMTOOLS_IDXSTATS -
[ed/3a337f] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRDEEP2:MIRDEEP2_PIGZ (112-5)                                      [ 52%] 59 of 112
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRDEEP2:MIRDEEP2_MAPPER                                            -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MIRDEEP2:MIRDEEP2_RUN                                               -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:CUSTOM_DUMPSOFTWAREVERSIONS                                         -
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:MULTIQC 
```

And the running parameters are

```
Core Nextflow options
  revision           : master
  runName            : cheesy_kalam
  containerEngine    : docker
  launchDir          : /data/Proyectos/miRNAs
  workDir            : /data/Proyectos/miRNAs/work
  projectDir         : /home/nanoneuro/.nextflow/assets/nf-core/smrnaseq
  userName           : nanoneuro
  profile            : docker
  configFiles        : /home/nanoneuro/.nextflow/assets/nf-core/smrnaseq/nextflow.config

Input/output options
  input              : samplesheet.csv
  outdir             : data/Gorostidi_BioDonosti_230711-24796800/results

Reference genome options
  genome             : GRCm38
  mirtrace_species   : mmu
  fasta              : s3://ngi-igenomes/igenomes/Mus_musculus/Ensembl/GRCm38/Sequence/WholeGenomeFasta/genome.fa
  mature             : https://www.mirbase.org/download_file/mature.fa/
  hairpin            : https://www.mirbase.org/download_file/hairpin.fa/

Trimming options
  clip_r1            : 1
  three_prime_clip_r1: 2

```

I guess that by binding the individual FASTQs can be a possible workaround to the issue.

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq \
   -profile docker \
   --input samplesheet.csv \
   --genome 'GRCm38' \
   --mirtrace_species 'mmu' \
   --protocol 'illumina' \
   --outdir data/Gorostidi_BioDonosti_230711-24796800/results \
   --mature https://www.mirbase.org/download_file/mature.fa/ \
   --hairpin https://www.mirbase.org/download_file/hairpin.fa/


Execution cancelled -- Finishing pending tasks before exit
-[nf-core/smrnaseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:MIRTRACE:MIRTRACE_RUN (1)'

Caused by:
  Process `NFCORE_SMRNASEQ:SMRNASEQ:MIRTRACE:MIRTRACE_RUN` input file name collision -- There are multiple input files for each of the following file names: 111-1.fastp.fastq.gz, 116-1.fastp.fastq.gz, 112-5.fastp.fastq.gz, 114-3.fastp.fastq.gz, 117-5.fastp.fastq.gz, 110-1.fastp.fastq.gz, 110-3.fastp.fastq.gz, 111-2.fastp.fastq.gz, 109-1.fastp.fastq.gz, 114-4.fastp.fastq.gz, 115-3.fastp.fastq.gz, 117-1.fastp.fastq.gz, 116-2.fastp.fastq.gz, 109-5.fastp.fastq.gz, 112-2.fastp.fastq.gz, 111-3.fastp.fastq.gz, 114-5.fastp.fastq.gz, 116-3.fastp.fastq.gz, 111-4.fastp.fastq.gz, 110-5.fastp.fastq.gz, 109-3.fastp.fastq.gz, 116-5.fastp.fastq.gz, 115-5.fastp.fastq.gz, 116-4.fastp.fastq.gz, 117-3.fastp.fastq.gz, 115-1.fastp.fastq.gz, 111-5.fastp.fastq.gz, 112-4.fastp.fastq.gz


Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### System information

Nextflow version: 23.04.1.5866
Hardware: Desktop
Executor: local
Container engine: Docker
OS: Ubuntu 22.04
Version of nf-core/smrnaseq: v2.2.1-gf7022ab

**Comment by apeltzer** [comment] 2023-08-30 07:43
This is a duplicate of https://github.com/nf-core/smrnaseq/issues/212 which is scheduled for 2.3.0. Currently not possible inside the pipeline, please concat your fastq files and then supply to the pipeline 👍🏻

**Closed by apeltzer** 2023-08-30 07:43 UTC
Labels: bug
