### ISSUE TITLE
Single end support: input settings

### ISSUE THREAD

**Issue by karthick1087** [nf-core/smrnaseq#115] opened 2021-10-18 10:47 UTC
Hi
Can I use single end reads from illumina as input. How can I distinguish control and case when I giving as input, since we use *.fastq.gz as input flag.

**Comment by apeltzer** [comment] 2022-10-11 08:02
Going to close this - I think the issue is not there so all good hopefully :)

**Closed by apeltzer** 2022-10-11 08:02 UTC
Labels: enhancement
