### ISSUE TITLE
Skip parameters not working correctly

### ISSUE THREAD

**Issue by Glfrey** [nf-core/smrnaseq#207] opened 2022-12-02 11:40 UTC
### Description of the bug

Implementing the `--skip_fastp --skip_fastqc` causes the pipeline error `Missing workflow output parameter: adapterseq`. 

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq --input experiment_info.csv --outdir run_test --genome GRCh37 -profile docker  -r 2.1.0 -c resource.config --skip_fastp --skip_fastqc

N E X T F L O W  ~  version 22.10.1
Launching `https://github.com/nf-core/smrnaseq` [elated_stallman] DSL2 - revision: 27514c40c0 [2.1.0]
WARN: Running with Protocol illumina
WARN: Therefore using Adapter: TGGAATTCTCGGGTGCCAAGG
WARN: Clipping 1 bases from R1
WARN: And clipping 2 bases from 3' end


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/smrnaseq v2.1.0
------------------------------------------------------
Core Nextflow options
  revision           : 2.1.0
  runName            : elated_stallman
  containerEngine    : docker
  launchDir          : /Users/gillianreynolds/Documents/small_RNAseq/clean_data_run
  workDir            : /Users/gillianreynolds/Documents/small_RNAseq/clean_data_run/work
  projectDir         : /Users/gillianreynolds/.nextflow/assets/nf-core/smrnaseq
  userName           : gillianreynolds
  profile            : docker
  configFiles        : /Users/gillianreynolds/.nextflow/assets/nf-core/smrnaseq/nextflow.config, /Users/gillianreynolds/Documents/small_RNAseq/clean_data_run/resource.config

Input/output options
  input              : experiment_info.csv
  outdir             : run_test

Reference genome options
  genome             : GRCh37
  mirtrace_species   : hsa
  fasta              : s3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa

Trimming options
  clip_r1            : 1
  three_prime_clip_r1: 2

Skipping pipeline steps
  skip_fastqc        : true
  skip_fastp         : true

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/smrnaseq for your analysis please cite:

* The pipeline
  https://zenodo.org/badge/latestdoi/140590861

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/smrnaseq/blob/master/CITATIONS.md
------------------------------------------------------
[-        ] process > NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK -
Missing workflow output parameter: adapterseq

 -- Check script '/Users/gillianreynolds/.nextflow/assets/nf-core/smrnaseq/./workflows/smrnaseq.nf' at line: 127 or see '.nextflow.log' file for more details
```

### System information

Nextflow version 22.10.1
MacBook Pro M1 
Docker container
MacOS
nfcore 2.1.0

**Comment by apeltzer** [comment] 2022-12-02 13:59
Yeah we need to initialize the `adapterseq` parameter then differently. @robsyme any idea?

**Comment by apeltzer** [comment] 2022-12-02 15:53
Duplicate of #208 - should aim to resolve it in one go.

**Closed by apeltzer** 2022-12-02 15:53 UTC
Labels: bug
