### ISSUE TITLE
mirdeep2 errors in v1.1.0 pipeline

### ISSUE THREAD

**Issue by mjsteinbaugh** [nf-core/smrnaseq#110] opened 2021-09-30 19:29 UTC
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/smrnaseq pipeline documentation](https://nf-co.re/nf-core/smrnaseq/usage)

## Description of the bug

I'm seeing mirdeep2 errors pop up with running the default configuration of the pipeline:

```
Error executing process > 'mirdeep2 (1)'

Caused by:
  Process `mirdeep2 (1)` terminated with an error exit status (255)

Command executed:

  perl -ane 's/[ybkmrsw]/N/ig;print;' hairpin.fa > hairpin_ok.fa
  sed 's/ .*//' genome.edited.fa | awk '$1 ~ /^>/ {gsub(/_/,"",$1); print; next} {print}' > genome_nowhitespace.fa

  miRDeep2.pl \
  30607-032.R1_trimmed_collapsed.fa \
  genome_nowhitespace.fa \
  30607-032.R1_trimmed_reads_vs_refdb.arf \

[...]

Error executing process > 'mirdeep2 (1)'

Caused by:
  Process `mirdeep2 (1)` terminated with an error exit status (255)

Command executed:

  perl -ane 's/[ybkmrsw]/N/ig;print;' hairpin.fa > hairpin_ok.fa
  sed 's/ .*//' genome.edited.fa | awk '$1 ~ /^>/ {gsub(/_/,"",$1); print; next} {print}' > genome_nowhitespace.fa

  miRDeep2.pl \
  30607-032.R1_trimmed_collapsed.fa \
  genome_nowhitespace.fa \
  30607-032.R1_trimmed_reads_vs_refdb.arf \

[...]

Error executing process > 'mirdeep2 (1)'

Caused by:
  Process `mirdeep2 (1)` terminated with an error exit status (255)

Command executed:

  perl -ane 's/[ybkmrsw]/N/ig;print;' hairpin.fa > hairpin_ok.fa
  sed 's/ .*//' genome.edited.fa | awk '$1 ~ /^>/ {gsub(/_/,"",$1); print; next} {print}' > genome_nowhitespace.fa

  miRDeep2.pl \
  30607-032.R1_trimmed_collapsed.fa \
  genome_nowhitespace.fa \
  30607-032.R1_trimmed_reads_vs_refdb.arf \
  mature.fa \
  none \
  hairpin_ok.fa \
  -d \
  -z _30607-032

Command exit status:
  255

Command output:


  #####################################
  #                                   #
  # miRDeep2.0.1.2                    #
  #                                   #
  # last change: 22/01/2019           #
  #                                   #
  #####################################

  miRDeep2 started at 18:54:23


  #Starting miRDeep2

Command error:
  #Starting miRDeep2
  /opt/conda/envs/nf-core-smrnaseq-1.1.0/bin/miRDeep2.pl 30607-032.R1_trimmed_collapsed.fa genome_nowhitespace.fa 30607-032.R1_trimmed_reads_vs_refdb.arf mature.fa none hairpin_ok.fa -d -z _3
0607-032

  miRDeep2 started at 18:54:23


  mkdir mirdeep_runs/run_30_09_2021_t_18_54_23_30607-032

  The mapped reference id chr22_KI270733v1_random from file 30607-032.R1_trimmed_reads_vs_refdb.arf is not an id of the genome file genome_nowhitespace.fa

Work dir:
  /opt/nextflow/work/work/fe/60acc7f099188ab8709ab98cf007f4

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

## Steps to reproduce

```sh
nextflow run 'nf-core/smrnaseq' -profile 'docker' \
    --genome 'GRCh38' \
    --input 'fastq/*.R1.fastq.gz'
```

I'm currently re-running the pipeline with `--skip_mirdeep` to see if it will successfully run through.

## System

- Hardware: AWS AMI Ubuntu 20
- Executor: EC2 / Docker
- OS: Ubuntu 20
- Version: 1.1.0 pipeline

## Nextflow Installation

- Version: 21.04.3

**Comment by mjsteinbaugh** [comment] 2021-09-30 21:20
OK the pipeline ran through with mirdeep disabled, but it seems to be stuck on this last step:

```
Waiting files transfer to complete (1 files)
```

**Comment by aubinthomas** [comment] 2021-10-06 11:41
I had just te same issue, the problem is that some genes were mapped (according to the .arf file) on chromosomes not listed in genome_nowhitespace.fa.

To resolve it I put in the bin directory of the pipeline (with rights to execution) the following perl script called patch.pl :


```
#!/usr/bin/env perl

###loading chromosome in genome_nowhitespace.fa
my %contigs;
open(IN, 'genome_nowhitespace.fa');
while(my $line=<IN>){
    
    if($line=~/>/){
        chomp($line);
        $line=~s/>//;
        $contigs{$line} = 1;
        #print STDERR $line,"\n";
    }
}
close(IN);

my $file_arf = $ARGV[0];
open(IN, $file_arf);
my @file = <IN>;
close(IN);
open(OUT, "> $file_arf");
for(my $i = 0; $i < scalar(@file); $i++){
    my @cc = split("\t", $file[$i]);
    if(exists $contigs{$cc[5]}){
        print OUT $file[$i];
    }
}

close(OUT);
```

and in the main.nf I modified the script part of mirdeep2 process:

```

script:
    """
    perl -ane 's/[ybkmrsw]/N/ig;print;' $hairpin > hairpin_ok.fa
    sed 's/ .*//' $refgenome | awk '\$1 ~ /^>/ {gsub(/_/,"",\$1); print; next} {print}' > genome_nowhitespace.fa
    patch.pl $reads_vs_refdb
    miRDeep2.pl \\
    $reads_collapsed \\
    genome_nowhitespace.fa \\
    $reads_vs_refdb \\
    $mature \\
    none \\
    hairpin_ok.fa \\
    -d \\
    -z _${reads_collapsed.simpleName}
    """
```


The script will discards these genes .

Hope this helps

**Comment by lpantano** [comment] 2021-10-06 12:59
Hi all,

Thanks for the information. We are migrating to DSL2 that is a big effort and it will take another couple of weeks to have it ready. I am incorporating the two processes for mirdeep2 and mirtrace and we can incorporate this. Is this using your own genome or the genome coming from the pipeline? Thanks!

**Comment by aubinthomas** [comment] 2021-10-06 13:07
I had this issues on human data by using as genome GRCh38  (--genome GRCh38)
For example with the public data SRR14736844

**Comment by lpantano** [comment] 2021-10-06 13:13
Did you try the devel branch, just out of curiosity?

**Comment by aubinthomas** [comment] 2021-10-06 13:18
No, I'll do it as soon as the version from the master has finished running, and I'll tell you!

**Comment by mjsteinbaugh** [comment] 2021-10-06 19:23
@lpantano I ran the NCBI GRCh38 genome as well via `--genome GRCh38`. Happy to help test this out and debug while you're working on the DSL2 update!

**Comment by v-cairoli** [comment] 2021-11-19 18:17
Hello!! I had the same issue with miRDeep2. I a just starting using linux and sequencing data.
Seing that @aubinthomas solved the problem with dev branch I wanted to know how do I use the dev branch (or if it is something that I need to install?) 
Thanks!

**Comment by lpantano** [comment] 2021-11-22 23:58
Hi, normally you could use the dev branch using the `-r` parameter with nextflow like `nextflow run nf-core/smrnaseq -r dev`. Something to be aware is the dev has a major change and the input is not anymore the path of the reads, you can follow the dev documentation here: https://github.com/nf-core/smrnaseq/blob/dev/docs/usage.md

**Comment by apeltzer** [comment] 2022-01-03 12:46
Will close this for now - @v-cairoli the latest changes have been merged  to `dev` and you could give this a try. It _should_ resolve your issues, if not please open a new issue 👍🏻

**Closed by apeltzer** 2022-01-03 12:46 UTC
Labels: bug
