### ISSUE TITLE
Error in NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE

### ISSUE THREAD

**Issue by alexmascension** [nf-core/smrnaseq#312] opened 2024-02-05 13:29 UTC
### Description of the bug

Im running the following command, using mirgenedb:

```
nextflow run nf-core/smrnaseq                                             
-r 2.2.4                                           
-profile docker                                             
-resume                                             
--max_cpus 9                                             
--max_memory 93.GB                                             
--max_time 500.h 
--skip_mirdeep 
--input work/test_human/samplesheets/SMRNASEQ_MIRGENE.csv 
--outdir results/test_human/SMRNASEQ_MIRGENE 
--genome GRCh38 
--mirgenedb 
--mirgenedb_gff database/smRNA/mirgenedb/hsa.gff 
--mirgenedb_mature $(pwd)/database/smRNA/mirgenedb/hsa.fas 
--mirgenedb_hairpin $(pwd)/database/smRNA/mirgenedb/hsa-pre.fas 
--fasta database/genomes/GRCh38/genome.fasta 
--bowtie_index database/indexes/GRCh38/BOWTIE
```

And I get the following error:

```
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE'

Caused by:
  Process `NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE` terminated with an error exit status (1)

Command executed:

  bowtie-build hsa.fas_igenome.fa_idx.fa fasta_bidx --threads 6
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE":
      bowtie: $(echo $(bowtie --version 2>&1) | sed 's/^.*bowtie-align-s version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  Settings:
    Output files: "fasta_bidx.*.ebwt"
    Line rate: 6 (line is 64 bytes)
    Lines per side: 1 (side is 64 bytes)
    Offset rate: 5 (one in 32)
    FTable chars: 10
    Strings: unpacked
    Max bucket size: default
    Max bucket size, sqrt multiplier: default
    Max bucket size, len divisor: 24
    Difference-cover sample period: 1024
    Endianness: little
    Actual local endianness: little
    Sanity checking: disabled
    Assertions: disabled
    Random seed: 0
    Sizeofs: void*:8, int:4, long:8, size_t:8
  Input files DNA, FASTA:
    hsa.fas_igenome.fa_idx.fa
  Reading reference sizes
    Time reading reference sizes: 00:00:00
  Total time for call to driver() for forward index: 00:00:00

Command error:
  Settings:
    Output files: "fasta_bidx.*.ebwt"
    Line rate: 6 (line is 64 bytes)
    Lines per side: 1 (side is 64 bytes)
    Offset rate: 5 (one in 32)
    FTable chars: 10
    Strings: unpacked
    Max bucket size: default
    Max bucket size, sqrt multiplier: default
    Max bucket size, len divisor: 24
    Difference-cover sample period: 1024
    Endianness: little
    Actual local endianness: little
    Sanity checking: disabled
    Assertions: disabled
    Random seed: 0
    Sizeofs: void*:8, int:4, long:8, size_t:8
  Input files DNA, FASTA:
    hsa.fas_igenome.fa_idx.fa
  Unable to read file magic number
  Reading reference sizes
  Warning: Empty input file
  Error: No unambiguous stretches of characters in the input.  Aborting...
    Time reading reference sizes: 00:00:00
  Total time for call to driver() for forward index: 00:00:00
  Command: bowtie-build --wrapper basic-0 --threads 6 hsa.fas_igenome.fa_idx.fa fasta_bidx 

Work dir:
  /data/Proyectos/NGS_pipeline/work/63/d9ebec3de933d7351832840280886b

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

The process works fine with mirtrace.

### Relevant files

[mirgene_db.zip](https://github.com/nf-core/smrnaseq/files/14166245/mirgene_db.zip)
[nextflow.log](https://github.com/nf-core/smrnaseq/files/14166253/nextflow.log)

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/smrnaseq/pull/305
```

**Comment by apeltzer** [comment] 2024-02-08 13:32
Please try using the `dev`version for now, this should resolve a number of issues / bugs.

**Comment by SoWhat1001** [comment] 2024-02-08 15:33
I am running into the same problem even though I am using the dev version

**Comment by apeltzer** [comment] 2024-02-08 17:02
Mirgenedb isn't clear to me. Looks like the input fastas are empty ?

**Comment by alexmascension** [comment] 2024-02-09 09:47
Hi! I get this error just by changing to `dev`:

```
ERROR ~ No such variable: index
```

The log says more specifically:
 ```
Feb-09 10:46:33.250 [main] DEBUG nextflow.Session - Session aborted -- Cause: No such property: index for class: nextflow.script.WorkflowBinding
```

**Comment by apeltzer** [comment] 2024-02-09 12:46
Weird, apart from that no changes to what you described in your first posting? We should probably add a test case I fear :-(

**Comment by alexmascension** [comment] 2024-02-09 13:26
Yeap, nothing else has changed.

**Comment by christopher-mohr** [comment] 2024-02-09 13:37
Is there more in the `nextflow.log` on the error? Could you share that?

**Comment by alexmascension** [comment] 2024-02-09 14:06
Sure! 

[nextflow.log](https://github.com/nf-core/smrnaseq/files/14222673/nextflow.log)

**Comment by christopher-mohr** [comment] 2024-02-14 10:33
Hi  @alexmascension, I cannot reproduce the error you posted five days ago using `dev`. I get the error you posted initially. Can you confirm this?

**Comment by alexmascension** [comment] 2024-02-14 11:00
Hi, I'm running the code again and I get the second error again. 

```
------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/smrnaseq v2.3.0-g18ae224
------------------------------------------------------
Core Nextflow options
  revision           : dev
  runName            : nauseous_curie
  containerEngine    : docker
  launchDir          : /data/Proyectos/NGS_pipeline
  workDir            : /data/Proyectos/NGS_pipeline/work
  projectDir         : /home/nanoneuro/.nextflow/assets/nf-core/smrnaseq
  userName           : nanoneuro
  profile            : docker
  configFiles        : 

Input/output options
  input              : work/test_human/samplesheets/SMRNASEQ_MIRGENE.csv
  outdir             : results/test_human/SMRNASEQ_MIRGENE

Reference genome options
  genome             : GRCh38
  mirgenedb          : true
  mirtrace_species   : hsa
  fasta              : database/genomes/GRCh38/genome.fasta
  mirgenedb_gff      : database/smRNA/mirgenedb/hsa.gff
  mirgenedb_mature   : /data/Proyectos/NGS_pipeline/database/smRNA/mirgenedb/hsa.fas
  mirgenedb_hairpin  : /data/Proyectos/NGS_pipeline/database/smRNA/mirgenedb/hsa-pre.fas
  bowtie_index       : database/indexes/GRCh38/BOWTIE

Trimming options
  clip_r1            : 0
  three_prime_clip_r1: 0

Skipping pipeline steps
  skip_mirdeep       : true

Max job request options
  max_cpus           : 9
  max_memory         : 84.GB
  max_time           : 500.h

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/smrnaseq for your analysis please cite:

* The pipeline
  https://zenodo.org/badge/latestdoi/140590861

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/smrnaseq/blob/master/CITATIONS.md

ERROR ~ No such variable: index

 -- Check script '/home/nanoneuro/.nextflow/assets/nf-core/smrnaseq/./workflows/smrnaseq.nf' at line: 165 or see '.nextflow.log' file for more details
```

[nextflow.log](https://github.com/nf-core/smrnaseq/files/14278411/nextflow.log)

However, nf-core continues if I remove the variable `--bowtie_index database/indexes/GRCh38/BOWTIE`, but it stops with the error I began with. 

```
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE'

Caused by:
  Process `NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE` terminated with an error exit status (1)

Command executed:

  bowtie-build hsa.fas_igenome.fa_idx.fa fasta_bidx --threads 6
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:SMRNASEQ:MIRNA_QUANT:INDEX_MATURE":
      bowtie: $(echo $(bowtie --version 2>&1) | sed 's/^.*bowtie-align-s version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  Settings:
    Output files: "fasta_bidx.*.ebwt"
    Line rate: 6 (line is 64 bytes)
    Lines per side: 1 (side is 64 bytes)
    Offset rate: 5 (one in 32)
    FTable chars: 10
    Strings: unpacked
    Max bucket size: default
    Max bucket size, sqrt multiplier: default
    Max bucket size, len divisor: 24
    Difference-cover sample period: 1024
    Endianness: little
    Actual local endianness: little
    Sanity checking: disabled
    Assertions: disabled
    Random seed: 0
    Sizeofs: void*:8, int:4, long:8, size_t:8
  Input files DNA, FASTA:
    hsa.fas_igenome.fa_idx.fa
  Reading reference sizes
    Time reading reference sizes: 00:00:00
  Total time for call to driver() for forward index: 00:00:00

Command error:
  Settings:
    Output files: "fasta_bidx.*.ebwt"
    Line rate: 6 (line is 64 bytes)
    Lines per side: 1 (side is 64 bytes)
    Offset rate: 5 (one in 32)
    FTable chars: 10
    Strings: unpacked
    Max bucket size: default
    Max bucket size, sqrt multiplier: default
    Max bucket size, len divisor: 24
    Difference-cover sample period: 1024
    Endianness: little
    Actual local endianness: little
    Sanity checking: disabled
    Assertions: disabled
    Random seed: 0
    Sizeofs: void*:8, int:4, long:8, size_t:8
  Input files DNA, FASTA:
    hsa.fas_igenome.fa_idx.fa
  Unable to read file magic number
  Reading reference sizes
  Warning: Empty input file
  Error: No unambiguous stretches of characters in the input.  Aborting...
  Command: bowtie-build --wrapper basic-0 --threads 6 hsa.fas_igenome.fa_idx.fa fasta_bidx 
    Time reading reference sizes: 00:00:00
  Total time for call to driver() for forward index: 00:00:00

Work dir:
  /data/Proyectos/NGS_pipeline/work/bf/a41903d3122c5f446a98faf0b75611

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```

[nexflow.2.log](https://github.com/nf-core/smrnaseq/files/14278547/nexflow.2.log)


The contents of the folder are `genome.1.ebwt  genome.2.ebwt  genome.3.ebwt  genome.4.ebwt  genome.rev.1.ebwt  genome.rev.2.ebwt`

If I change `--bowtie_index database/indexes/GRCh38/BOWTIE` with `--bowtie_index database/indexes/GRCh38/BOWTIE/genome` I get the same error.

**Comment by christopher-mohr** [comment] 2024-02-14 11:10
Okay, I think we might need a separate issue for the `--bowtie_index` error. Could you try running it again without `--bowtie_index` but add the following to your call `--mirgenedb_species "Hsa"` please.

**Comment by alexmascension** [comment] 2024-02-14 12:53
Hi! 

With `--mirgenedb_species "Hsa"` the program works fine! 

Do I open a new issue for the `--bowtie_index` error?

Thanks!

**Comment by christopher-mohr** [comment] 2024-02-14 13:02
Yes please, I will also leave this issue open and close it with a PR where I add a check to make sure the `--mirgenedb_species` parameter is set.

**Comment by alexmascension** [comment] 2024-02-14 13:23
Fine!

**Comment by apeltzer** [comment] 2024-02-22 12:41
Dev fixes this issue now, thanks for reporting @alexmascension

**Closed by apeltzer** 2024-02-22 12:41 UTC
Labels: enhancement
